language: csharp
solution: BitZenyConfigCreator.sln
matrix:
    include:
        - os: linux #Ubuntu 
          dist: trusty
          sudo: required
          dotnet: 2.0.0
        - os: osx #OSX 10.12
          osx_image: xcode7.3
          dotnet: 2.0.0
mono: none
script:
    - dotnet restore
    - dotnet build
